let app,auth,db,currentUser=null,isAdmin=false,forms=[],responses=[],departments=[],members=[],activeFormId='',editMode='new',editingId='',draftQuestions=[];
const $=id=>document.getElementById(id);
const front=$('front'),frontMain=$('frontMain'),formStatus=$('formStatus'),admin=$('admin'),loginMask=$('loginMask'),loginBtn=$('loginBtn'),loginMsg=$('loginMsg'),adminUser=$('adminUser'),activeFormSelect=$('activeFormSelect'),activeFormLabel=$('activeFormLabel'),formsTable=$('formsTable'),resultsTable=$('resultsTable'),questionEditor=$('questionEditor');

function col(name){return db.collection(name)}
function doc(name,id){return col(name).doc(id)}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function attr(v){return esc(v)}
function toast(message){let t=$('toast');t.textContent=message;t.style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.style.display='none',2600)}
function formatDeadline(value){if(!value)return '';let d=new Date(value);return Number.isNaN(d.getTime())?value:d.toLocaleString('zh-TW',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'})}
function deadlinePassed(value){if(!value)return false;let d=new Date(value);return !Number.isNaN(d.getTime())&&d<new Date()}
function imageUrl(value){let v=String(value||'').trim();if(!v)return '';if(/^assets\/[\w./-]+$/i.test(v))return v;try{let u=new URL(v,location.href);return /^https?:$/.test(u.protocol)?u.href:''}catch(e){return''}}
function formRouteId(){let m=location.hash.match(/^#form\/([^/?#]+)/);return m?decodeURIComponent(m[1]):''}

async function init(){
  if(!window.firebase||typeof firebaseConfig==='undefined'||!firebaseConfig.apiKey){frontMain.innerHTML='<div class="successCard"><h2>尚未設定 Firebase</h2><p>請確認 js/config.js 已正確上傳。</p></div>';return}
  app=firebase.initializeApp(firebaseConfig);auth=firebase.auth();db=firebase.firestore();
  window.addEventListener('hashchange',applyRoute);
  auth.onAuthStateChanged(async user=>{currentUser=user;isAdmin=false;if(user){try{isAdmin=await checkAdmin(user)}catch(e){console.error(e)}if(isAdmin){adminUser.textContent=user.email||'';loginMask.style.display='none';await loadAdminData()}}applyRoute()});
  await loadPublicData();applyRoute();
}

async function checkAdmin(user){let direct=await doc('users',user.uid).get();if(direct.exists){let u=direct.data();if(u.enabled!==false&&String(u.role||'').toLowerCase()==='admin')return true}let q=await col('users').where('email','==',user.email).limit(1).get();if(q.empty)return false;let u=q.docs[0].data();return u.enabled!==false&&String(u.role||'').toLowerCase()==='admin'}
async function loadPublicData(){let [fs,ds,ms]=await Promise.all([col('universalForms').get(),col('departments').get(),col('members').get()]);forms=fs.docs.map(x=>({id:x.id,...x.data()})).sort((a,b)=>(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0));departments=ds.docs.map(x=>({id:x.id,...x.data()})).sort((a,b)=>(a.sortOrder??999)-(b.sortOrder??999));members=ms.docs.map(x=>({id:x.id,...x.data()})).filter(x=>x.active!==false).sort((a,b)=>String(a.employeeNo||a.empNo||'').localeCompare(String(b.employeeNo||b.empNo||''),'zh-Hant',{numeric:true}));let route=formRouteId();activeFormId=(route&&forms.some(f=>f.id===route)?route:(forms.find(f=>f.state==='open')||forms[0])?.id)||''}
async function loadAdminData(){await loadPublicData();await loadResponses();renderAdmin()}
async function loadResponses(){if(!isAdmin||!activeFormId){responses=[];return}try{let q=await col('universalResponses').where('formId','==',activeFormId).get();responses=q.docs.map(x=>({id:x.id,...x.data()})).sort((a,b)=>(b.submittedAt?.seconds||0)-(a.submittedAt?.seconds||0))}catch(e){console.warn(e);responses=[]}}

function applyRoute(){let wantsAdmin=location.hash==='#admin';if(wantsAdmin&&isAdmin){front.style.display='none';admin.style.display='block';loginMask.style.display='none';renderAdmin();return}admin.style.display='none';front.style.display='block';if(wantsAdmin&&!isAdmin)loginMask.style.display='grid';else loginMask.style.display='none';renderFront()}
function openAdmin(){history.pushState(null,'','#admin');applyRoute()}
function closeLogin(){loginMask.style.display='none';history.replaceState(null,'','#form/'+encodeURIComponent(activeFormId||''));applyRoute()}
async function loginGoogle(){if(!auth){loginMsg.textContent='登入服務尚未完成初始化，請重新整理頁面後再試一次。';return}loginBtn.disabled=true;loginBtn.textContent='登入處理中…';loginMsg.textContent='';try{let p=new firebase.auth.GoogleAuthProvider();p.setCustomParameters({prompt:'select_account'});await auth.signInWithPopup(p);if(!isAdmin)loginMsg.textContent='正在確認管理員權限…'}catch(e){loginMsg.textContent=e.code==='auth/popup-closed-by-user'?'已取消登入。':(e.message||'登入失敗')}finally{loginBtn.disabled=false;loginBtn.textContent='使用 Google 登入'}}
async function logout(){await auth.signOut();history.replaceState(null,'','#form/'+encodeURIComponent(activeFormId||''));applyRoute()}
function showFront(){history.pushState(null,'','#form/'+encodeURIComponent(activeFormId||''));applyRoute()}

function activeForm(){return forms.find(f=>f.id===activeFormId)||null}
function renderFront(){let f=forms.find(x=>x.id===(formRouteId()||activeFormId))||forms.find(x=>x.state==='open')||forms[0];if(!f){formStatus.textContent='尚無問卷';frontMain.innerHTML='<div class="successCard"><h2>目前尚無可填寫問卷</h2><p>請洽管理者建立問卷。</p></div>';return}activeFormId=f.id;let closed=f.state!=='open'||deadlinePassed(f.deadline);formStatus.textContent=closed?'問卷已關閉':'問卷開放中';let heroImage=imageUrl(f.imageUrl);frontMain.innerHTML=`<section class="formHero"><h1>${esc(f.title)}</h1><p>${esc(f.description||'')}</p>${f.deadline?`<span class="deadlineBadge">請於 ${esc(formatDeadline(f.deadline))} 前完成</span>`:''}${heroImage?`<img class="referenceImage" src="${attr(heroImage)}" alt="問卷參考圖片">`:''}</section>${closed?'<div class="successCard" style="margin-top:18px"><h2>本問卷目前未開放填寫</h2></div>':`<form id="publicForm" class="questionList" onsubmit="submitResponse(event)">${f.identityMode==='member'?renderIdentityBlock(f):''}${(f.questions||[]).map(renderPublicQuestion).join('')}<div class="submitArea"><button id="submitBtn" class="btn primary" type="submit">確認並送出</button><span id="submitNote" class="questionHelp"></span></div></form>`}`}

function allowedDepartmentNames(f){let selected=Array.isArray(f.targetDepartments)?f.targetDepartments:[];let all=departments.map(d=>d.name||d.departmentName||d.department||'').filter(Boolean);return selected.length?all.filter(x=>selected.includes(x)):all}
function renderIdentityBlock(f){let deps=allowedDepartmentNames(f);return `<section class="questionCard identityCard"><label class="title">填寫者資料 <span class="required">*</span></label><div class="identityGrid"><label>部門<select id="identityDepartment" required onchange="updateIdentityMembers(this.value)"><option value="">請選擇部門</option>${deps.map(d=>`<option value="${attr(d)}">${esc(d)}</option>`).join('')}</select></label><label>姓名<select id="identityMember" required onchange="updateIdentityEmployee(this.value)" disabled><option value="">請先選擇部門</option></select></label><label>員工編號<input id="identityEmployeeNo" class="readonlyField" readonly placeholder="自動帶入"></label></div></section>`}
function updateIdentityMembers(department){let select=$('identityMember'),list=members.filter(m=>(m.department||m.departmentName||'')===department);select.innerHTML='<option value="">請選擇姓名</option>'+list.map(m=>`<option value="${attr(m.id)}">${esc(m.name)}（${esc(m.employeeNo||m.empNo||'')}）</option>`).join('');select.disabled=!department;$('identityEmployeeNo').value=''}
function updateIdentityEmployee(id){let m=members.find(x=>x.id===id);$('identityEmployeeNo').value=m?.employeeNo||m?.empNo||''}

function renderPublicQuestion(q,index){let required=q.required?'<span class="required"> *</span>':'';let title=`${index+1}. ${esc(q.title||'未命名題目')}${required}`;let help=q.help?`<div class="questionHelp">${esc(q.help)}</div>`:'';let img=imageUrl(q.imageUrl),image=img?`<img class="questionImage" src="${attr(img)}" alt="${attr(q.title||'參考圖片')}">`:'';if(q.type==='image')return `<section class="questionCard">${image}<label class="title">${title}</label>${help}</section>`;let name='q_'+q.id,req=q.required?'required':'';let input='';if(q.type==='long')input=`<textarea name="${attr(name)}" ${req}></textarea>`;else if(q.type==='single'||q.type==='multiple'){let t=q.type==='multiple'?'checkbox':'radio',choiceRequired=q.type==='single'?req:'';input=`<div class="choiceList">${(q.options||[]).map(o=>`<label class="choice"><input type="${t}" name="${attr(name)}" value="${attr(o)}" ${choiceRequired}>${esc(o)}</label>`).join('')}</div>`}else if(q.type==='dropdown'||q.type==='department'){let opts=q.type==='department'?departments.map(d=>d.name||d.departmentName||'').filter(Boolean):(q.options||[]);input=`<select name="${attr(name)}" ${req}><option value="">請選擇</option>${opts.map(o=>`<option value="${attr(o)}">${esc(o)}</option>`).join('')}</select>`}else input=`<input type="text" name="${attr(name)}" ${req}>`;return `<section class="questionCard">${image}<label class="title">${title}</label>${help}${input}</section>`}

async function submitResponse(event){event.preventDefault();let f=activeForm();if(!f||f.state!=='open'||deadlinePassed(f.deadline))return alert('問卷已關閉，請重新整理頁面');let identity={};if(f.identityMode==='member'){let departmentName=$('identityDepartment')?.value||'',memberId=$('identityMember')?.value||'',m=members.find(x=>x.id===memberId);if(!departmentName||!m)return alert('請選擇您的部門與姓名');if((m.department||m.departmentName)!==departmentName)return alert('人員資料與部門不相符，請重新選擇');identity={departmentName,memberId,memberName:m.name||'',employeeNo:m.employeeNo||m.empNo||''}}let fd=new FormData(event.target),answers={};for(let q of(f.questions||[])){if(q.type==='image')continue;let name='q_'+q.id;if(q.type==='multiple')answers[q.id]=fd.getAll(name);else answers[q.id]=String(fd.get(name)||'').trim();if(q.required&&(!answers[q.id]||(Array.isArray(answers[q.id])&&!answers[q.id].length)))return alert('請完成必填題目：'+q.title)}if(!confirm('確認送出這份問卷嗎？'))return;let btn=$('submitBtn');btn.disabled=true;btn.textContent='送出中…';try{await col('universalResponses').add({formId:f.id,formTitle:f.title,...identity,answers,submittedAt:firebase.firestore.FieldValue.serverTimestamp(),submittedAtText:new Date().toLocaleString('zh-TW')});frontMain.innerHTML='<div class="successCard"><h2>✓ 問卷已成功送出</h2><p>感謝您的填寫。</p><button class="btn" onclick="location.reload()">返回問卷</button></div>'}catch(e){console.error(e);alert('送出失敗，請檢查網路後再試一次');btn.disabled=false;btn.textContent='確認並送出'}}

function showPanel(id,button){document.querySelectorAll('.panel').forEach(p=>p.classList.remove('active'));$(id).classList.add('active');document.querySelectorAll('.nav').forEach(n=>n.classList.remove('active'));if(button)button.classList.add('active');$('panelTitle').textContent=({formsPanel:'問卷管理',editorPanel:'問卷編輯',resultsPanel:'填寫結果'})[id]||'通用問卷後台';if(id==='resultsPanel')renderResults()}
function renderAdmin(){activeFormSelect.innerHTML='<option value="">請選擇問卷</option>'+forms.map(f=>`<option value="${attr(f.id)}" ${f.id===activeFormId?'selected':''}>${esc(f.title)}</option>`).join('');let f=activeForm();activeFormLabel.textContent=f?'目前問卷：'+f.title:'尚未選擇問卷';$('formCount').textContent=forms.length;$('currentFormName').textContent=f?.title||'—';$('responseCount').textContent=responses.length;renderFormsTable();renderResults()}
function table(headers,rows){return `<div class="tableWrap"><table><thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.join('')||`<tr><td colspan="${headers.length}">尚無資料</td></tr>`}</tbody></table></div>`}
function renderFormsTable(){formsTable.innerHTML=table(['問卷','狀態','截止時間','題數','操作'],forms.map(f=>`<tr><td><b>${esc(f.title)}</b><br><small>${esc(f.id)}</small></td><td>${esc(stateLabel(f.state))}</td><td>${esc(formatDeadline(f.deadline)||'未設定')}</td><td>${(f.questions||[]).length}</td><td><div class="buttonRow"><button class="btn" onclick="editForm('${attr(f.id)}')">編輯</button><button class="btn" onclick="selectForm('${attr(f.id)}')">查看結果</button><button class="btn" onclick="copyFormLink('${attr(f.id)}')">複製網址</button><button class="btn danger" onclick="deleteForm('${attr(f.id)}')">刪除</button></div></td></tr>`))}
function stateLabel(v){return({draft:'草稿',open:'開放中',closed:'已關閉'})[v]||v}
async function selectForm(id){activeFormId=id;await loadResponses();renderAdmin();showPanel('resultsPanel')}

function renderTargetDepartments(selected=null){if(selected===null)selected=[...document.querySelectorAll('.targetDepartment:checked')].map(x=>x.value);let enabled=$('identityMode').value==='member',box=$('targetDepartmentBox');box.innerHTML=departments.map(d=>{let n=d.name||d.departmentName||d.department||'';return `<label class="departmentChoice"><input type="checkbox" class="targetDepartment" value="${attr(n)}" ${selected.includes(n)?'checked':''}>${esc(n)}</label>`}).join('')||'<span class="questionHelp">尚無部門資料</span>';document.querySelector('.identitySettings')?.classList.toggle('disabled',!enabled);box.querySelectorAll('input').forEach(x=>x.disabled=!enabled)}
function startNewForm(){editMode='new';editingId='';draftQuestions=[];$('editorHeading').textContent='新增問卷';$('editorMode').textContent='新增模式';$('saveFormBtn').textContent='建立問卷';$('formTitle').value='';$('formDescription').value='';$('formDeadline').value='';$('formState').value='draft';$('formImageUrl').value='';$('identityMode').value='member';renderTargetDepartments([]);renderQuestionEditor()}
function editForm(id){let f=forms.find(x=>x.id===id);if(!f)return;editMode='edit';editingId=id;draftQuestions=JSON.parse(JSON.stringify(f.questions||[]));$('editorHeading').textContent='編輯問卷：'+f.title;$('editorMode').textContent='編輯模式';$('saveFormBtn').textContent='儲存變更';$('formTitle').value=f.title||'';$('formDescription').value=f.description||'';$('formDeadline').value=(f.deadline||'').slice(0,16);$('formState').value=f.state||'draft';$('formImageUrl').value=f.imageUrl||'';$('identityMode').value=f.identityMode||'none';renderTargetDepartments(f.targetDepartments||[]);renderQuestionEditor();showPanel('editorPanel')}
function cancelEdit(){showPanel('formsPanel');startNewForm()}
function addQuestion(type='short'){draftQuestions.push({id:'q_'+Date.now()+'_'+Math.random().toString(36).slice(2,6),type,title:'',required:false,options:[],imageUrl:'',help:''});renderQuestionEditor()}
function updateQuestion(i,key,value){if(key==='options')draftQuestions[i][key]=value.split('\n').map(x=>x.trim()).filter(Boolean);else draftQuestions[i][key]=value}
function moveQuestion(i,delta){let j=i+delta;if(j<0||j>=draftQuestions.length)return;[draftQuestions[i],draftQuestions[j]]=[draftQuestions[j],draftQuestions[i]];renderQuestionEditor()}
function removeQuestion(i){if(confirm('確定移除此題？')){draftQuestions.splice(i,1);renderQuestionEditor()}}
function renderQuestionEditor(){questionEditor.innerHTML=draftQuestions.map((q,i)=>`<div class="questionEdit"><div class="questionGrid"><label>題目名稱<input value="${attr(q.title)}" oninput="updateQuestion(${i},'title',this.value)"></label><label>題型<select onchange="updateQuestion(${i},'type',this.value);renderQuestionEditor()">${[['short','簡答'],['long','長文'],['single','單選'],['multiple','複選'],['dropdown','下拉選單'],['department','部門選單'],['image','圖片／說明']].map(x=>`<option value="${x[0]}" ${q.type===x[0]?'selected':''}>${x[1]}</option>`).join('')}</select></label><label>必填<select onchange="updateQuestion(${i},'required',this.value==='true')"><option value="false" ${!q.required?'selected':''}>否</option><option value="true" ${q.required?'selected':''}>是</option></select></label></div>${['single','multiple','dropdown'].includes(q.type)?`<label class="optionsField">選項（每行一個）<textarea oninput="updateQuestion(${i},'options',this.value)">${esc((q.options||[]).join('\n'))}</textarea></label>`:''}<div class="questionGrid"><label>說明文字<input value="${attr(q.help||'')}" oninput="updateQuestion(${i},'help',this.value)"></label><label>參考圖片網址<input value="${attr(q.imageUrl||'')}" oninput="updateQuestion(${i},'imageUrl',this.value)"></label></div><div class="miniActions"><button class="btn" onclick="moveQuestion(${i},-1)">上移</button><button class="btn" onclick="moveQuestion(${i},1)">下移</button><button class="btn danger" onclick="removeQuestion(${i})">移除</button></div></div>`).join('')||'<div class="questionHelp">尚未建立題目，請按「新增題目」。</div>'}

async function saveForm(){let title=$('formTitle').value.trim();if(!title)return alert('請輸入問卷標題');if(!draftQuestions.length)return alert('請至少建立一個題目');if(draftQuestions.some(q=>!q.title.trim()))return alert('每一題都需要題目名稱');if(draftQuestions.some(q=>['single','multiple','dropdown'].includes(q.type)&&!(q.options||[]).length))return alert('選擇題至少需要一個選項');let identityMode=$('identityMode').value,targetDepartments=identityMode==='member'?[...document.querySelectorAll('.targetDepartment:checked')].map(x=>x.value):[];let id=editMode==='edit'?editingId:'form_'+Date.now(),data={title,description:$('formDescription').value.trim(),deadline:$('formDeadline').value,state:$('formState').value,imageUrl:$('formImageUrl').value.trim(),identityMode,targetDepartments,questions:draftQuestions,updatedAt:firebase.firestore.FieldValue.serverTimestamp()};if(editMode==='new')data.createdAt=firebase.firestore.FieldValue.serverTimestamp();let btn=$('saveFormBtn');btn.disabled=true;btn.textContent='儲存中…';try{await doc('universalForms',id).set(data,{merge:true});activeFormId=id;await loadAdminData();showPanel('formsPanel');toast(editMode==='edit'?'問卷變更已儲存':'問卷已建立')}catch(e){console.error(e);alert('問卷儲存失敗')}finally{btn.disabled=false;btn.textContent=editMode==='edit'?'儲存變更':'建立問卷'}}

async function createUniformTemplate(){if(forms.some(f=>f.templateKey==='uniform-jacket')&&!confirm('已經有外套尺寸範本，仍要再建立一份嗎？'))return;let id='uniform_'+Date.now(),questions=[{id:'size',type:'dropdown',title:'選擇您的外套尺寸',required:true,options:['XS','S','M','L','XL','2XL','3XL','4XL'],help:'請參考下方尺寸資訊選擇'},{id:'reference',type:'image',title:'外套款式、尺寸表與丈量位置參考',required:false,options:[],imageUrl:'assets/uniform-survey-reference.jpg',help:'目前使用原 Google 問卷截圖；取得原始圖片後可在後台替換。'}],data={title:'【環興科技】立領撞色外套尺寸調查表',description:'為統計同仁外套尺寸，請依照尺寸表與丈量方式選擇合適尺寸。\n請於期限內完成填寫，如有疑問請洽承辦人。',deadline:'',state:'draft',imageUrl:'',identityMode:'member',targetDepartments:[],questions,templateKey:'uniform-jacket',createdAt:firebase.firestore.FieldValue.serverTimestamp(),updatedAt:firebase.firestore.FieldValue.serverTimestamp()};await doc('universalForms',id).set(data);activeFormId=id;await loadAdminData();editForm(id);toast('已建立外套尺寸調查範本，請選擇開放部門並設定截止時間')}

async function deleteForm(id){if(!confirm('確定刪除此問卷？既有回覆不會自動刪除。'))return;await doc('universalForms',id).delete();if(activeFormId===id)activeFormId='';await loadAdminData();toast('問卷已刪除')}
function copyFormLink(id=activeFormId){if(!id)return alert('請先選擇問卷');let url=location.href.split('#')[0]+'#form/'+encodeURIComponent(id);navigator.clipboard?.writeText(url).then(()=>toast('問卷網址已複製')).catch(()=>prompt('請複製問卷網址',url))}

function answerText(q,r){let v=r.answers?.[q.id];return Array.isArray(v)?v.join('、'):String(v??'')}
function renderResults(){let f=activeForm();$('resultCaption').textContent=f?`${f.title}：共 ${responses.length} 份回覆`:'請先選擇問卷。';if(!f){resultsTable.innerHTML='';return}let qs=(f.questions||[]).filter(q=>q.type!=='image'),identityHeaders=f.identityMode==='member'?['部門','姓名','員工編號']:[];resultsTable.innerHTML=table(['送出時間',...identityHeaders,...qs.map(q=>q.title)],responses.map(r=>`<tr><td>${esc(r.submittedAtText||'')}</td>${f.identityMode==='member'?`<td>${esc(r.departmentName||'')}</td><td>${esc(r.memberName||'')}</td><td>${esc(r.employeeNo||'')}</td>`:''}${qs.map(q=>`<td>${esc(answerText(q,r))}</td>`).join('')}</tr>`))}
function exportResults(){let f=activeForm();if(!f)return alert('請先選擇問卷');let qs=(f.questions||[]).filter(q=>q.type!=='image'),rows=responses.map(r=>{let row={'送出時間':r.submittedAtText||''};if(f.identityMode==='member'){row['部門']=r.departmentName||'';row['姓名']=r.memberName||'';row['員工編號']=r.employeeNo||''}qs.forEach(q=>row[q.title]=answerText(q,r));return row}),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rows),'填寫結果');XLSX.writeFile(wb,(f.title||'問卷')+'_結果.xlsx')}

init().catch(e=>{console.error(e);frontMain.innerHTML='<div class="successCard"><h2>系統載入失敗</h2><p>'+esc(e.message||e)+'</p></div>'});
