let app,auth,db,currentUser=null,isAdmin=false,forms=[],responses=[],departments=[],members=[],activeFormId='',editMode='new',editingId='',draftQuestions=[],editingResponseId='',memberEditMode='view',editingMemberId='',submissionLocksPrepared=false;
const $=id=>document.getElementById(id);
const front=$('front'),frontMain=$('frontMain'),formStatus=$('formStatus'),admin=$('admin'),loginMask=$('loginMask'),loginBtn=$('loginBtn'),loginMsg=$('loginMsg'),adminUser=$('adminUser'),activeFormSelect=$('activeFormSelect'),activeFormLabel=$('activeFormLabel'),formsTable=$('formsTable'),resultsTable=$('resultsTable'),questionEditor=$('questionEditor');

function col(name){return db.collection(name)}
function doc(name,id){return col(name).doc(id)}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function attr(v){return esc(v)}
function toast(message){let t=$('toast');t.textContent=message;t.style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.style.display='none',2600)}
function formatDeadline(value){if(!value)return '';let d=new Date(value);return Number.isNaN(d.getTime())?value:d.toLocaleString('zh-TW',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'})}
function deadlinePassed(value){if(!value)return false;let d=new Date(value);return !Number.isNaN(d.getTime())&&d<new Date()}
function driveFileId(value){let v=String(value||'').trim();if(!v)return '';try{let u=new URL(v);if(!/(^|\.)drive\.google\.com$/i.test(u.hostname))return '';let pathMatch=u.pathname.match(/\/file\/d\/([^/]+)/i)||u.pathname.match(/\/d\/([^/]+)/i);return pathMatch?.[1]||u.searchParams.get('id')||''}catch(e){return''}}
function imageUrl(value){let v=String(value||'').trim();if(!v)return '';if(/^assets\/[\w./-]+$/i.test(v))return v;let driveId=driveFileId(v);if(driveId)return `https://drive.google.com/thumbnail?id=${encodeURIComponent(driveId)}&sz=w1600`;try{let u=new URL(v,location.href);return /^https?:$/.test(u.protocol)?u.href:''}catch(e){return''}}
function imagePreviewHtml(value,alt='圖片預覽'){let url=imageUrl(value);return url?`<img src="${attr(url)}" alt="${attr(alt)}" onerror="this.parentElement.innerHTML='<div class=&quot;imagePreviewError&quot;>圖片無法顯示，請確認 Google Drive 分享權限。</div>'">`:''}
function previewHeaderImage(){$('headerImagePreview').innerHTML=imagePreviewHtml($('formImageUrl').value,'頁首圖片預覽')}
function updateQuestionImage(i,value){draftQuestions[i].imageUrl=value;let preview=$('questionImagePreview_'+i);if(preview)preview.innerHTML=imagePreviewHtml(value,draftQuestions[i].title||'參考圖片預覽')}
function formRouteId(){let m=location.hash.match(/^#form\/([^/?#]+)/);return m?decodeURIComponent(m[1]):''}

async function init(){
  if(!window.firebase||typeof firebaseConfig==='undefined'||!firebaseConfig.apiKey){frontMain.innerHTML='<div class="successCard"><h2>尚未設定 Firebase</h2><p>請確認 js/config.js 已正確上傳。</p></div>';return}
  app=firebase.initializeApp(firebaseConfig);auth=firebase.auth();db=firebase.firestore();
  window.addEventListener('hashchange',applyRoute);
  auth.onAuthStateChanged(async user=>{currentUser=user;isAdmin=false;if(user){try{isAdmin=await checkAdmin(user)}catch(e){console.error(e)}if(isAdmin){adminUser.textContent=user.email||'';loginMask.style.display='none';await loadAdminData()}}applyRoute()});
  await loadPublicData();applyRoute();
}

async function checkAdmin(user){let direct=await doc('users',user.uid).get();if(direct.exists){let u=direct.data();if(u.enabled!==false&&String(u.role||'').toLowerCase()==='admin')return true}let q=await col('users').where('email','==',user.email).limit(1).get();if(q.empty)return false;let u=q.docs[0].data();return u.enabled!==false&&String(u.role||'').toLowerCase()==='admin'}
async function loadPublicData(){let [fs,ds,ms]=await Promise.all([col('universalForms').get(),col('departments').get(),col('members').get()]);forms=fs.docs.map(x=>({id:x.id,...x.data()})).sort((a,b)=>(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0));departments=ds.docs.map(x=>({id:x.id,...x.data()})).sort((a,b)=>(a.sortOrder??999)-(b.sortOrder??999));let depOrder=new Map(departments.map((d,i)=>[d.name||d.departmentName||d.department||'',i]));members=ms.docs.map(x=>({id:x.id,...x.data()})).sort((a,b)=>{let ad=a.department||a.departmentName||'',bd=b.department||b.departmentName||'',diff=(depOrder.get(ad)??9999)-(depOrder.get(bd)??9999);if(diff)return diff;return String(a.employeeNo||a.empNo||'').localeCompare(String(b.employeeNo||b.empNo||''),'zh-Hant',{numeric:true})||String(a.name||'').localeCompare(String(b.name||''),'zh-Hant')});let route=formRouteId();activeFormId=(route&&forms.some(f=>f.id===route)?route:(forms.find(f=>f.state==='open')||forms[0])?.id)||''}
async function loadAdminData(){await loadPublicData();if(!submissionLocksPrepared)await prepareSubmissionLocks();await loadResponses();renderAdmin()}
async function loadResponses(){if(!isAdmin||!activeFormId){responses=[];return}try{let q=await col('universalResponses').where('formId','==',activeFormId).get(),items=q.docs.map(x=>({id:x.id,...x.data()})).sort((a,b)=>(b.submittedAt?.seconds||0)-(a.submittedAt?.seconds||0));if(await normalizeExistingResponseIds(items)){q=await col('universalResponses').where('formId','==',activeFormId).get();items=q.docs.map(x=>({id:x.id,...x.data()})).sort((a,b)=>(b.submittedAt?.seconds||0)-(a.submittedAt?.seconds||0))}responses=items}catch(e){console.warn(e);responses=[]}}
async function normalizeExistingResponseIds(items){let changed=false,ids=new Set(items.map(x=>x.id));for(let r of items){if(!r.memberId)continue;let target=`${r.formId}__${r.memberId}`;if(ids.has(target))continue;let {id,...data}=r;try{await doc('universalResponses',target).set(data);await doc('universalResponses',id).delete();ids.add(target);changed=true}catch(e){console.warn('既有回覆防重複轉換失敗',e)}}return changed}
async function prepareSubmissionLocks(){try{let [responseSnap,lockSnap]=await Promise.all([col('universalResponses').get(),col('universalResponseLocks').get()]),items=responseSnap.docs.map(x=>({id:x.id,...x.data()})).sort((a,b)=>(b.submittedAt?.seconds||0)-(a.submittedAt?.seconds||0)),responseIds=new Set(items.map(x=>x.id)),lockIds=new Set(lockSnap.docs.map(x=>x.id)),handled=new Set();for(let r of items){if(!r.formId||!r.memberId)continue;let key=`${r.formId}__${r.memberId}`;if(handled.has(key))continue;handled.add(key);if(!responseIds.has(key)){let {id,...data}=r;await doc('universalResponses',key).set(data);await doc('universalResponses',id).delete();responseIds.add(key)}if(!lockIds.has(key)){await doc('universalResponseLocks',key).set({formId:r.formId,memberId:r.memberId,createdAt:firebase.firestore.FieldValue.serverTimestamp()});lockIds.add(key)}}}catch(e){console.warn('建立既有回覆鎖定紀錄失敗，請確認 v1.10 Firestore 規則',e)}finally{submissionLocksPrepared=true}}

function applyRoute(){let wantsAdmin=location.hash==='#admin';if(wantsAdmin&&isAdmin){front.style.display='none';admin.style.display='block';loginMask.style.display='none';renderAdmin();return}admin.style.display='none';front.style.display='block';if(wantsAdmin&&!isAdmin)loginMask.style.display='grid';else loginMask.style.display='none';renderFront()}
function openAdmin(){history.pushState(null,'','#admin');applyRoute()}
function closeLogin(){loginMask.style.display='none';history.replaceState(null,'','#form/'+encodeURIComponent(activeFormId||''));applyRoute()}
async function loginGoogle(){if(!auth){loginMsg.textContent='登入服務尚未完成初始化，請重新整理頁面後再試一次。';return}loginBtn.disabled=true;loginBtn.textContent='登入處理中…';loginMsg.textContent='';try{let p=new firebase.auth.GoogleAuthProvider();p.setCustomParameters({prompt:'select_account'});await auth.signInWithPopup(p);if(!isAdmin)loginMsg.textContent='正在確認管理員權限…'}catch(e){loginMsg.textContent=e.code==='auth/popup-closed-by-user'?'已取消登入。':(e.message||'登入失敗')}finally{loginBtn.disabled=false;loginBtn.textContent='使用 Google 登入'}}
async function logout(){await auth.signOut();history.replaceState(null,'','#form/'+encodeURIComponent(activeFormId||''));applyRoute()}
function showFront(){history.pushState(null,'','#form/'+encodeURIComponent(activeFormId||''));applyRoute()}

function activeForm(){return forms.find(f=>f.id===activeFormId)||null}
function renderFront(){let f=forms.find(x=>x.id===(formRouteId()||activeFormId))||forms.find(x=>x.state==='open')||forms[0];if(!f){formStatus.textContent='尚無問卷';frontMain.innerHTML='<div class="successCard"><h2>目前尚無可填寫問卷</h2><p>請洽管理者建立問卷。</p></div>';return}activeFormId=f.id;let closed=f.state!=='open'||deadlinePassed(f.deadline);formStatus.textContent=closed?'問卷已關閉':'問卷開放中';let heroImage=imageUrl(f.imageUrl);frontMain.innerHTML=`<section class="formHero"><h1>${esc(f.title)}</h1><p>${esc(f.description||'')}</p>${f.deadline?`<span class="deadlineBadge">請於 ${esc(formatDeadline(f.deadline))} 前完成</span>`:''}${heroImage?`<img class="referenceImage" src="${attr(heroImage)}" alt="問卷參考圖片">`:''}</section>${closed?'<div class="successCard" style="margin-top:18px"><h2>本問卷目前未開放填寫</h2></div>':`<form id="publicForm" class="questionList" onsubmit="submitResponse(event)">${f.identityMode==='member'?renderIdentityBlock(f):''}${(f.questions||[]).map(renderPublicQuestion).join('')}<div class="submitArea"><button id="submitBtn" class="btn primary" type="submit">確認並送出</button><span id="submitNote" class="questionHelp"></span></div></form>`}`}

function allowedDepartmentNames(f){let selected=Array.isArray(f.targetDepartments)?f.targetDepartments:[];let all=departments.map(d=>d.name||d.departmentName||d.department||'').filter(Boolean);return selected.length?all.filter(x=>selected.includes(x)):all}
function renderIdentityBlock(f){let deps=allowedDepartmentNames(f);return `<section class="questionCard identityCard"><label class="title">填寫者資料 <span class="required">*</span></label><div class="identityGrid"><label>部門<select id="identityDepartment" required onchange="updateIdentityMembers(this.value)"><option value="">請選擇部門</option>${deps.map(d=>`<option value="${attr(d)}">${esc(d)}</option>`).join('')}</select></label><label>姓名<select id="identityMember" required disabled><option value="">請先選擇部門</option></select></label></div></section>`}
function updateIdentityMembers(department){let select=$('identityMember'),list=members.filter(m=>m.active!==false&&(m.department||m.departmentName||'')===department);select.innerHTML='<option value="">請選擇姓名</option>'+list.map(m=>`<option value="${attr(m.id)}">${esc(m.name)}</option>`).join('');select.disabled=!department}

function renderPublicQuestion(q){let required=q.required?'<span class="required"> *</span>':'';let title=`${esc(q.title||'未命名題目')}${required}`;let help=q.help?`<div class="questionHelp">${esc(q.help)}</div>`:'';let img=imageUrl(q.imageUrl),image=img?`<img class="questionImage" src="${attr(img)}" alt="${attr(q.title||'參考圖片')}">`:'';if(q.type==='image')return `<section class="questionCard"><label class="title">${title}</label>${help}${image}</section>`;let name='q_'+q.id,req=q.required?'required':'';let input='';if(q.type==='long')input=`<textarea name="${attr(name)}" ${req}></textarea>`;else if(q.type==='single'||q.type==='multiple'){let t=q.type==='multiple'?'checkbox':'radio',choiceRequired=q.type==='single'?req:'';input=`<div class="choiceList">${(q.options||[]).map(o=>`<label class="choice"><input type="${t}" name="${attr(name)}" value="${attr(o)}" ${choiceRequired}>${esc(o)}</label>`).join('')}</div>`}else if(q.type==='dropdown'||q.type==='department'){let opts=q.type==='department'?departments.map(d=>d.name||d.departmentName||'').filter(Boolean):(q.options||[]);input=`<select name="${attr(name)}" ${req}><option value="">請選擇</option>${opts.map(o=>`<option value="${attr(o)}">${esc(o)}</option>`).join('')}</select>`}else input=`<input type="text" name="${attr(name)}" ${req}>`;return `<section class="questionCard"><label class="title">${title}</label>${help}${image}${input}</section>`}

async function submitResponse(event){event.preventDefault();let f=activeForm();if(!f||f.state!=='open'||deadlinePassed(f.deadline))return alert('問卷已關閉，請重新整理頁面');let identity={},note=$('submitNote');note.textContent='';note.classList.remove('submitError');if(f.identityMode==='member'){let departmentName=$('identityDepartment')?.value||'',memberId=$('identityMember')?.value||'',m=members.find(x=>x.id===memberId);if(!departmentName||!m)return alert('請選擇您的部門與姓名');if(m.active===false)return alert('這位同仁目前為停用狀態，無法填寫');if((m.department||m.departmentName)!==departmentName)return alert('人員資料與部門不相符，請重新選擇');identity={departmentName,memberId,memberName:m.name||'',employeeNo:m.employeeNo||m.empNo||''}}let fd=new FormData(event.target),answers={};for(let q of(f.questions||[])){if(q.type==='image')continue;let name='q_'+q.id;if(q.type==='multiple')answers[q.id]=fd.getAll(name);else answers[q.id]=String(fd.get(name)||'').trim();if(q.required&&(!answers[q.id]||(Array.isArray(answers[q.id])&&!answers[q.id].length)))return alert('請完成必填題目：'+q.title)}let responseKey=f.identityMode==='member'?`${f.id}__${identity.memberId}`:'',lockRef=responseKey?doc('universalResponseLocks',responseKey):null;if(lockRef){note.textContent='正在確認是否已填寫…';try{let lock=await lockRef.get();if(lock.exists){let message='您已填寫過這份問卷，無法重複送出。如需更正，請洽管理員。';note.textContent=message;note.classList.add('submitError');alert(message);return}}catch(e){console.error(e);note.textContent='目前無法確認填寫狀態，請稍後再試。';note.classList.add('submitError');alert('無法確認是否已填寫，為避免重複資料，本次不會送出。');return}}note.textContent='';if(!confirm('確認送出這份問卷嗎？送出後如需更正，請洽管理員。'))return;let btn=$('submitBtn');btn.disabled=true;btn.textContent='送出中…';let payload={formId:f.id,formTitle:f.title,...identity,answers,submittedAt:firebase.firestore.FieldValue.serverTimestamp(),submittedAtText:new Date().toLocaleString('zh-TW')};try{let batch=db.batch(),responseRef=responseKey?doc('universalResponses',responseKey):col('universalResponses').doc();batch.set(responseRef,payload);if(lockRef)batch.set(lockRef,{formId:f.id,memberId:identity.memberId,createdAt:firebase.firestore.FieldValue.serverTimestamp()});await batch.commit();frontMain.innerHTML='<div class="successCard"><h2>✓ 問卷已成功送出</h2><p>每位同仁限填一次；如需更正請洽管理員。</p><button class="btn" onclick="location.reload()">返回問卷</button></div>'}catch(e){console.error(e);if(f.identityMode==='member'&&e.code==='permission-denied'){let message='您已填寫過這份問卷，無法重複送出。如需更正，請洽管理員。';note.textContent=message;note.classList.add('submitError');alert(message)}else{note.textContent='送出失敗，請稍後再試。';note.classList.add('submitError');alert('送出失敗，請檢查網路後再試一次')}btn.disabled=false;btn.textContent='確認並送出'}}

function showPanel(id,button){document.querySelectorAll('.panel').forEach(p=>p.classList.remove('active'));$(id).classList.add('active');document.querySelectorAll('.nav').forEach(n=>n.classList.remove('active'));if(button)button.classList.add('active');$('panelTitle').textContent=({formsPanel:'問卷管理',editorPanel:'問卷編輯',membersPanel:'人員管理',resultsPanel:'填寫結果'})[id]||'通用問卷後台';if(id==='resultsPanel')renderResults();if(id==='membersPanel')renderMemberPanel()}
function renderAdmin(){activeFormSelect.innerHTML='<option value="">請選擇問卷</option>'+forms.map(f=>`<option value="${attr(f.id)}" ${f.id===activeFormId?'selected':''}>${esc(f.title)}</option>`).join('');let f=activeForm();activeFormLabel.textContent=f?'目前問卷：'+f.title:'尚未選擇問卷';$('formCount').textContent=forms.length;$('currentFormName').textContent=f?.title||'—';$('responseCount').textContent=responses.length;renderFormsTable();renderMemberPanel();renderResults()}
function table(headers,rows){return `<div class="tableWrap"><table><thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.join('')||`<tr><td colspan="${headers.length}">尚無資料</td></tr>`}</tbody></table></div>`}
function renderFormsTable(){formsTable.innerHTML=table(['問卷','狀態','截止時間','題數','操作'],forms.map(f=>`<tr><td><b>${esc(f.title)}</b><br><small>${esc(f.id)}</small></td><td>${esc(stateLabel(f.state))}</td><td>${esc(formatDeadline(f.deadline)||'未設定')}</td><td>${(f.questions||[]).length}</td><td><div class="buttonRow"><button class="btn" onclick="editForm('${attr(f.id)}')">編輯</button><button class="btn" onclick="selectForm('${attr(f.id)}')">查看結果</button><button class="btn" onclick="copyFormLink('${attr(f.id)}')">複製網址</button><button class="btn danger" onclick="deleteForm('${attr(f.id)}')">刪除</button></div></td></tr>`))}
function stateLabel(v){return({draft:'草稿',open:'開放中',closed:'已關閉'})[v]||v}
async function selectForm(id){activeFormId=id;await loadResponses();renderAdmin();showPanel('resultsPanel')}

function renderTargetDepartments(selected=null){if(selected===null)selected=[...document.querySelectorAll('.targetDepartment:checked')].map(x=>x.value);let enabled=$('identityMode').value==='member',box=$('targetDepartmentBox');box.innerHTML=departments.map(d=>{let n=d.name||d.departmentName||d.department||'';return `<label class="departmentChoice"><input type="checkbox" class="targetDepartment" value="${attr(n)}" ${selected.includes(n)?'checked':''}>${esc(n)}</label>`}).join('')||'<span class="questionHelp">尚無部門資料</span>';document.querySelector('.identitySettings')?.classList.toggle('disabled',!enabled);box.querySelectorAll('input').forEach(x=>x.disabled=!enabled)}
function startNewForm(){editMode='new';editingId='';draftQuestions=[];$('editorHeading').textContent='新增問卷';$('editorMode').textContent='新增模式';$('saveFormBtn').textContent='建立問卷';$('formTitle').value='';$('formDescription').value='';$('formDeadline').value='';$('formState').value='draft';$('formImageUrl').value='';previewHeaderImage();$('identityMode').value='member';renderTargetDepartments([]);renderQuestionEditor()}
function editForm(id){let f=forms.find(x=>x.id===id);if(!f)return;editMode='edit';editingId=id;draftQuestions=JSON.parse(JSON.stringify(f.questions||[]));$('editorHeading').textContent='編輯問卷：'+f.title;$('editorMode').textContent='編輯模式';$('saveFormBtn').textContent='儲存變更';$('formTitle').value=f.title||'';$('formDescription').value=f.description||'';$('formDeadline').value=(f.deadline||'').slice(0,16);$('formState').value=f.state||'draft';$('formImageUrl').value=f.imageUrl||'';previewHeaderImage();$('identityMode').value=f.identityMode||'none';renderTargetDepartments(f.targetDepartments||[]);renderQuestionEditor();showPanel('editorPanel')}
function cancelEdit(){showPanel('formsPanel');startNewForm()}
function addQuestion(type='short'){draftQuestions.push({id:'q_'+Date.now()+'_'+Math.random().toString(36).slice(2,6),type,title:'',required:false,options:[],imageUrl:'',help:''});renderQuestionEditor()}
function updateQuestion(i,key,value){if(key==='options')draftQuestions[i][key]=value.split('\n').map(x=>x.trim()).filter(Boolean);else draftQuestions[i][key]=value}
function moveQuestion(i,delta){let j=i+delta;if(j<0||j>=draftQuestions.length)return;[draftQuestions[i],draftQuestions[j]]=[draftQuestions[j],draftQuestions[i]];renderQuestionEditor()}
function removeQuestion(i){if(confirm('確定移除此題？')){draftQuestions.splice(i,1);renderQuestionEditor()}}
function renderQuestionEditor(){questionEditor.innerHTML=draftQuestions.map((q,i)=>`<div class="questionEdit"><div class="questionGrid"><label>題目名稱<input value="${attr(q.title)}" oninput="updateQuestion(${i},'title',this.value)"></label><label>題型<select onchange="updateQuestion(${i},'type',this.value);renderQuestionEditor()">${[['short','簡答'],['long','長文'],['single','單選'],['multiple','複選'],['dropdown','下拉選單'],['department','部門選單'],['image','圖片／說明']].map(x=>`<option value="${x[0]}" ${q.type===x[0]?'selected':''}>${x[1]}</option>`).join('')}</select></label><label>必填<select onchange="updateQuestion(${i},'required',this.value==='true')"><option value="false" ${!q.required?'selected':''}>否</option><option value="true" ${q.required?'selected':''}>是</option></select></label></div>${['single','multiple','dropdown'].includes(q.type)?`<label class="optionsField">選項（每行一個）<textarea oninput="updateQuestion(${i},'options',this.value)">${esc((q.options||[]).join('\n'))}</textarea></label>`:''}<div class="questionGrid"><label>說明文字<input value="${attr(q.help||'')}" oninput="updateQuestion(${i},'help',this.value)"></label><div class="questionImageField"><label>參考圖片網址<input value="${attr(q.imageUrl||'')}" placeholder="可貼 Google Drive 分享網址" oninput="updateQuestionImage(${i},this.value)"></label><p>Drive 圖片需開啟「知道連結的使用者皆可查看」。</p><div id="questionImagePreview_${i}" class="imagePreview">${imagePreviewHtml(q.imageUrl,q.title||'參考圖片預覽')}</div></div></div><div class="miniActions"><button class="btn" onclick="moveQuestion(${i},-1)">上移</button><button class="btn" onclick="moveQuestion(${i},1)">下移</button><button class="btn danger" onclick="removeQuestion(${i})">移除</button></div></div>`).join('')||'<div class="questionHelp">尚未建立題目，請按「新增題目」。</div>'}

async function saveForm(){let title=$('formTitle').value.trim();if(!title)return alert('請輸入問卷標題');if(!draftQuestions.length)return alert('請至少建立一個題目');if(draftQuestions.some(q=>!q.title.trim()))return alert('每一題都需要題目名稱');if(draftQuestions.some(q=>['single','multiple','dropdown'].includes(q.type)&&!(q.options||[]).length))return alert('選擇題至少需要一個選項');let identityMode=$('identityMode').value,targetDepartments=identityMode==='member'?[...document.querySelectorAll('.targetDepartment:checked')].map(x=>x.value):[];let id=editMode==='edit'?editingId:'form_'+Date.now(),data={title,description:$('formDescription').value.trim(),deadline:$('formDeadline').value,state:$('formState').value,imageUrl:$('formImageUrl').value.trim(),identityMode,targetDepartments,questions:draftQuestions,updatedAt:firebase.firestore.FieldValue.serverTimestamp()};if(editMode==='new')data.createdAt=firebase.firestore.FieldValue.serverTimestamp();let btn=$('saveFormBtn');btn.disabled=true;btn.textContent='儲存中…';try{await doc('universalForms',id).set(data,{merge:true});activeFormId=id;await loadAdminData();showPanel('formsPanel');toast(editMode==='edit'?'問卷變更已儲存':'問卷已建立')}catch(e){console.error(e);alert('問卷儲存失敗')}finally{btn.disabled=false;btn.textContent=editMode==='edit'?'儲存變更':'建立問卷'}}

async function createUniformTemplate(){if(forms.some(f=>f.templateKey==='uniform-jacket')&&!confirm('已經有外套尺寸範本，仍要再建立一份嗎？'))return;let id='uniform_'+Date.now(),questions=[{id:'size',type:'dropdown',title:'選擇您的外套尺寸',required:true,options:['XS','S','M','L','XL','2XL','3XL','4XL'],help:'請參考下方尺寸資訊選擇'},{id:'reference',type:'image',title:'外套款式、尺寸表與丈量位置參考',required:false,options:[],imageUrl:'assets/uniform-survey-reference.jpg',help:'目前使用原 Google 問卷截圖；取得原始圖片後可在後台替換。'}],data={title:'【環興科技】立領撞色外套尺寸調查表',description:'為統計同仁外套尺寸，請依照尺寸表與丈量方式選擇合適尺寸。\n請於期限內完成填寫，如有疑問請洽承辦人。',deadline:'',state:'draft',imageUrl:'',identityMode:'member',targetDepartments:[],questions,templateKey:'uniform-jacket',createdAt:firebase.firestore.FieldValue.serverTimestamp(),updatedAt:firebase.firestore.FieldValue.serverTimestamp()};await doc('universalForms',id).set(data);activeFormId=id;await loadAdminData();editForm(id);toast('已建立外套尺寸調查範本，請選擇開放部門並設定截止時間')}

async function deleteForm(id){if(!confirm('確定刪除此問卷？既有回覆不會自動刪除。'))return;await doc('universalForms',id).delete();if(activeFormId===id)activeFormId='';await loadAdminData();toast('問卷已刪除')}
function copyFormLink(id=activeFormId){if(!id)return alert('請先選擇問卷');let url=location.href.split('#')[0]+'#form/'+encodeURIComponent(id);navigator.clipboard?.writeText(url).then(()=>toast('問卷網址已複製')).catch(()=>prompt('請複製問卷網址',url))}

function answerText(q,r){let v=r.answers?.[q.id];return Array.isArray(v)?v.join('、'):String(v??'')}
const chartColors=['#287c78','#e89a5b','#5478c7','#a56cc1','#d8606f','#76a85e','#d3a72f','#4f9eaa','#8c7a6b','#6a86a3'];
function percentage(count,total){return total?Math.round(count*1000/total)/10:0}
function optionCounts(q){let map=new Map((q.options||[]).map(o=>[String(o),0]));for(let r of responses){let value=r.answers?.[q.id],values=Array.isArray(value)?value:[value];for(let item of values){let key=String(item??'').trim();if(key)map.set(key,(map.get(key)||0)+1)}}return [...map.entries()].map(([label,count])=>({label,count}))}
function pieHtml(title,items,denominator=responses.length){let shown=items.filter(x=>x.count>0),sum=shown.reduce((n,x)=>n+x.count,0),cursor=0,segments=shown.map((x,i)=>{let start=cursor,end=cursor+(sum?x.count/sum*100:0);cursor=end;return `${chartColors[i%chartColors.length]} ${start}% ${end}%`}).join(','),background=sum?`conic-gradient(${segments})`:'#e8eef0';return `<div class="analysisCard"><h3>${esc(title)}</h3><div class="pieLayout"><div class="pieChart" style="background:${attr(background)}" role="img" aria-label="${attr(title)}圓餅圖"></div><div class="chartLegend">${items.map((x,i)=>`<div class="legendRow"><span class="legendDot" style="background:${chartColors[i%chartColors.length]}"></span><span>${esc(x.label)}</span><strong>${x.count} 人・${percentage(x.count,denominator)}%</strong></div>`).join('')||'<span class="questionHelp">尚無資料</span>'}</div></div></div>`}
function multipleAnalysisHtml(q){let items=optionCounts(q),total=responses.length;return `<div class="analysisCard"><h3>${esc(q.title)}</h3><div class="barList">${items.map(x=>{let p=percentage(x.count,total);return `<div><div class="barRowHead"><span>${esc(x.label)}</span><strong>${x.count} 人・${p}%</strong></div><div class="barTrack"><div class="barFill" style="width:${p}%"></div></div></div>`}).join('')||'<span class="questionHelp">尚無資料</span>'}</div></div>`}
function textAnalysisHtml(q){let items=responses.map(r=>({who:r.memberName||r.employeeNo||'未具名',text:String(r.answers?.[q.id]??'').trim()})).filter(x=>x.text);return `<div class="analysisCard"><h3>${esc(q.title)} <small>（${items.length} 則）</small></h3><div class="textAnswerList">${items.map(x=>`<div class="textAnswer"><b>${esc(x.who)}</b><p>${esc(x.text)}</p></div>`).join('')||'<span class="questionHelp">尚無文字回覆</span>'}</div></div>`}
function renderAnalysis(f){let total=responses.length,departmentsUsed=new Set(responses.map(r=>r.departmentName).filter(Boolean)),latest=responses[0]?.submittedAtText||'—',depMap=new Map();responses.forEach(r=>{let d=r.departmentName||'未填部門';depMap.set(d,(depMap.get(d)||0)+1)});let cards=[];if(f.identityMode==='member')cards.push(pieHtml('部門分布',[...depMap].map(([label,count])=>({label,count})),total));for(let q of(f.questions||[])){if(q.type==='image')continue;if(['single','dropdown','department'].includes(q.type))cards.push(pieHtml(q.title,optionCounts(q),total));else if(q.type==='multiple')cards.push(multipleAnalysisHtml(q));else if(['short','long'].includes(q.type))cards.push(textAnalysisHtml(q))}return `<div class="analysisSummary"><div class="analysisMetric"><span>總填寫人數</span><b>${total}</b></div><div class="analysisMetric"><span>填寫部門數</span><b>${departmentsUsed.size}</b></div><div class="analysisMetric"><span>最近填寫時間</span><b style="font-size:15px">${esc(latest)}</b></div></div>${total?`<div class="analysisGrid">${cards.join('')}</div>`:'<div class="emptyAnalysis">目前尚無填寫資料，收到回覆後會自動產生統計。</div>'}`}
function renderResults(){let f=activeForm();$('resultCaption').textContent=f?`${f.title}：共 ${responses.length} 份回覆`:'請先選擇問卷。';if(!f){$('resultAnalysis').innerHTML='';resultsTable.innerHTML='';return}$('resultAnalysis').innerHTML=renderAnalysis(f);let qs=(f.questions||[]).filter(q=>q.type!=='image'),identityHeaders=f.identityMode==='member'?['部門','姓名','員工編號']:[];resultsTable.innerHTML=table(['送出時間',...identityHeaders,...qs.map(q=>q.title),'操作'],responses.map(r=>`<tr><td>${esc(r.submittedAtText||'')}</td>${f.identityMode==='member'?`<td>${esc(r.departmentName||'')}</td><td>${esc(r.memberName||'')}</td><td>${esc(r.employeeNo||'')}</td>`:''}${qs.map(q=>`<td>${esc(answerText(q,r))}</td>`).join('')}<td><div class="buttonRow"><button class="btn" onclick="openResponseEditor('${attr(r.id)}')">編輯</button><button class="btn danger" onclick="deleteResponse('${attr(r.id)}')">刪除</button></div></td></tr>`))}

function editMemberOptions(department,selected=''){return members.filter(m=>(m.department||m.departmentName||'')===department&&(m.active!==false||m.id===selected)).map(m=>`<option value="${attr(m.id)}" ${m.id===selected?'selected':''}>${esc(m.name||'')}（${esc(m.employeeNo||m.empNo||'')}）</option>`).join('')}

function memberDepartmentOptions(selected=''){return departments.map(d=>d.name||d.departmentName||d.department||'').filter(Boolean).map(d=>`<option value="${attr(d)}" ${d===selected?'selected':''}>${esc(d)}</option>`).join('')}
function renderMemberPanel(){let target=$('membersTable');if(!target)return;let keyword=String($('memberSearch')?.value||'').trim().toLowerCase(),list=members.filter(m=>!keyword||`${m.department||m.departmentName||''} ${m.name||''} ${m.employeeNo||m.empNo||''}`.toLowerCase().includes(keyword));$('memberCountLabel').textContent=`顯示 ${list.length}／${members.length} 人`;target.innerHTML=table(['部門','姓名','員工編號','狀態','操作'],list.map(m=>{let active=m.active!==false;return `<tr><td>${esc(m.department||m.departmentName||'')}</td><td><b>${esc(m.name||'')}</b></td><td>${esc(m.employeeNo||m.empNo||'')}</td><td><span class="statusBadge ${active?'active':'inactive'}">${active?'啟用':'停用'}</span></td><td><div class="buttonRow"><button class="btn" onclick="editMember('${attr(m.id)}')">修改</button><button class="btn" onclick="toggleMember('${attr(m.id)}',${active?'false':'true'})">${active?'停用':'啟用'}</button><button class="btn danger" onclick="deleteMember('${attr(m.id)}')">刪除</button></div></td></tr>`}))}
function fillMemberEditor(m=null){$('memberDepartment').innerHTML='<option value="">請選擇部門</option>'+memberDepartmentOptions(m?.department||m?.departmentName||'');$('memberName').value=m?.name||'';$('memberEmployeeNo').value=m?.employeeNo||m?.empNo||'';$('memberActive').value=String(m?.active!==false)}
function startNewMember(){memberEditMode='new';editingMemberId='';$('memberEditorHeading').textContent='新增人員';$('memberEditorMode').textContent='新增模式';$('saveMemberBtn').textContent='新增人員';fillMemberEditor();$('memberEditor').style.display='block';$('memberName').focus()}
function editMember(id){let m=members.find(x=>x.id===id);if(!m)return;memberEditMode='edit';editingMemberId=id;$('memberEditorHeading').textContent='修改人員：'+(m.name||'');$('memberEditorMode').textContent='編輯模式';$('saveMemberBtn').textContent='儲存變更';fillMemberEditor(m);$('memberEditor').style.display='block';$('memberEditor').scrollIntoView({behavior:'smooth',block:'start'})}
function cancelMemberEdit(){memberEditMode='view';editingMemberId='';$('memberEditor').style.display='none'}
async function saveMember(){let department=$('memberDepartment').value,name=$('memberName').value.trim(),employeeNo=$('memberEmployeeNo').value.trim();if(!department||!name||!employeeNo)return alert('請完整填寫部門、姓名與員工編號');let duplicate=members.find(m=>String(m.employeeNo||m.empNo||'').trim()===employeeNo&&m.id!==editingMemberId);if(duplicate)return alert(`員工編號 ${employeeNo} 已由 ${duplicate.name||'其他人員'} 使用`);let data={department,name,employeeNo,active:$('memberActive').value==='true',updatedAt:firebase.firestore.FieldValue.serverTimestamp()},btn=$('saveMemberBtn');btn.disabled=true;btn.textContent='儲存中…';try{if(memberEditMode==='new'){data.createdAt=firebase.firestore.FieldValue.serverTimestamp();await col('members').add(data)}else await doc('members',editingMemberId).set(data,{merge:true});let wasNew=memberEditMode==='new';cancelMemberEdit();await loadAdminData();showPanel('membersPanel');toast(wasNew?'人員已新增，兩套系統將同步使用':'人員資料已更新')}catch(e){console.error(e);alert('人員資料儲存失敗')}finally{btn.disabled=false;btn.textContent=memberEditMode==='edit'?'儲存變更':'新增人員'}}
async function toggleMember(id,active){let m=members.find(x=>x.id===id);if(!m)return;if(!active&&!confirm(`確定停用 ${m.name||'這位人員'}？停用後兩套調查系統的前台都不會顯示。`))return;await doc('members',id).set({active,updatedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true});await loadAdminData();showPanel('membersPanel');toast(active?'人員已啟用':'人員已停用')}
async function deleteMember(id){let m=members.find(x=>x.id===id);if(!m)return;if(!confirm(`確定刪除 ${m.name||'這位人員'}（${m.employeeNo||m.empNo||''}）？\n建議優先使用「停用」，以保留歷史資料關聯。`))return;if(!confirm('再次確認永久刪除這筆共用人員資料？兩套系統都會同步消失。'))return;await doc('members',id).delete();await loadAdminData();showPanel('membersPanel');toast('共用人員資料已刪除')}
function chooseMemberImport(){$('memberImportInput').click()}
function memberWorkbook(rows,sheetName='人員名單'){let wb=XLSX.utils.book_new(),ws=XLSX.utils.json_to_sheet(rows,{header:['部門','姓名','員工編號','狀態']});ws['!cols']=[{wch:16},{wch:14},{wch:14},{wch:10}];XLSX.utils.book_append_sheet(wb,ws,sheetName);return wb}
function downloadMemberTemplate(){XLSX.writeFile(memberWorkbook([{'部門':'行政部','姓名':'王小明','員工編號':'7901','狀態':'啟用'}],'匯入範本'),'人員匯入標準範本.xlsx')}
function exportMembers(){let rows=members.map(m=>({'部門':m.department||m.departmentName||'','姓名':m.name||'','員工編號':m.employeeNo||m.empNo||'','狀態':m.active===false?'停用':'啟用'}));XLSX.writeFile(memberWorkbook(rows),'共用人員名單.xlsx')}
function memberCell(row,names){let keys=Object.keys(row);for(let name of names){let key=keys.find(k=>String(k).replace(/^\uFEFF/,'').trim()===name);if(key!==undefined)return row[key]}return''}
async function importMembers(file){if(!file)return;let result=$('memberImportResult');result.className='memberImportResult';result.style.display='block';result.textContent=`正在讀取 ${file.name}…`;try{let data=await file.arrayBuffer(),wb=XLSX.read(data,{type:'array'}),rows=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:''});if(!rows.length)throw new Error('檔案內沒有可匯入的資料');let validDepartments=new Set(departments.map(d=>d.name||d.departmentName||d.department||'').filter(Boolean)),existingByNo=new Map(members.map(m=>[String(m.employeeNo||m.empNo||'').trim(),m]).filter(x=>x[0])),seen=new Set(),errors=[],items=[];rows.forEach((row,index)=>{let line=index+2,department=String(memberCell(row,['部門'])).trim(),name=String(memberCell(row,['姓名'])).trim(),employeeNo=String(memberCell(row,['員工編號','員編'])).trim(),status=String(memberCell(row,['狀態'])).trim();if(!department||!name||!employeeNo){errors.push(`第 ${line} 列：部門、姓名與員工編號為必填`);return}if(!validDepartments.has(department)){errors.push(`第 ${line} 列：找不到部門「${department}」`);return}if(seen.has(employeeNo)){errors.push(`第 ${line} 列：員工編號 ${employeeNo} 在檔案中重複`);return}seen.add(employeeNo);let active=!['停用','否','false','0','no'].includes(status.toLowerCase());items.push({existing:existingByNo.get(employeeNo)||null,data:{department,name,employeeNo,active,updatedAt:firebase.firestore.FieldValue.serverTimestamp()}})});let addCount=items.filter(x=>!x.existing).length,updateCount=items.length-addCount,summary=`可匯入 ${items.length} 筆（新增 ${addCount}、更新 ${updateCount}）`+(errors.length?`\n另有 ${errors.length} 筆錯誤將略過：\n${errors.slice(0,8).join('\n')}${errors.length>8?'\n…':''}`:'');result.textContent=summary;if(!items.length){result.className='memberImportResult error';return alert(summary)}if(!confirm(summary+'\n\n確定寫入共用人員名單嗎？兩套系統會同步使用。')){result.textContent='已取消匯入';return}for(let item of items){if(item.existing)await doc('members',item.existing.id).set(item.data,{merge:true});else{item.data.createdAt=firebase.firestore.FieldValue.serverTimestamp();await col('members').add(item.data)}}await loadAdminData();showPanel('membersPanel');result=$('memberImportResult');result.className='memberImportResult success';result.textContent=`匯入完成：新增 ${addCount} 筆、更新 ${updateCount} 筆${errors.length?'，略過 '+errors.length+' 筆錯誤':''}`;toast('共用人員名單匯入完成')}catch(e){console.error(e);result.className='memberImportResult error';result.textContent='匯入失敗：'+(e.message||e)}}
function openResponseEditor(id){let f=activeForm(),r=responses.find(x=>x.id===id);if(!f||!r)return;editingResponseId=id;$('responseEditCaption').textContent=`${r.memberName||'未具名'} ${r.employeeNo?`（${r.employeeNo}）`:''}`;let identity='';if(f.identityMode==='member'){let deps=departments.map(d=>d.name||d.departmentName||d.department||'').filter(Boolean);identity=`<div class="editIdentityGrid"><label>部門<select id="editDepartment" onchange="refreshEditMemberOptions(this.value)"><option value="">請選擇部門</option>${deps.map(d=>`<option value="${attr(d)}" ${d===r.departmentName?'selected':''}>${esc(d)}</option>`).join('')}</select></label><label>姓名<select id="editMember" onchange="refreshEditEmployee()"><option value="">請選擇姓名</option>${editMemberOptions(r.departmentName||'',r.memberId||'')}</select></label><label>員工編號<input id="editEmployeeNo" value="${attr(r.employeeNo||'')}" readonly></label></div>`}let questions=(f.questions||[]).filter(q=>q.type!=='image').map(q=>editQuestionHtml(q,r.answers?.[q.id])).join('');$('responseEditBody').innerHTML=identity+questions;$('responseEditMask').style.display='grid'}
function editQuestionHtml(q,value){let name='edit_q_'+q.id,label=`<label>${esc(q.title)}</label>`;if(q.type==='multiple'){let selected=Array.isArray(value)?value:[];return `<div class="editQuestion">${label}<div class="editChoices">${(q.options||[]).map(o=>`<label><input type="checkbox" name="${attr(name)}" value="${attr(o)}" ${selected.includes(o)?'checked':''}>${esc(o)}</label>`).join('')}</div></div>`}if(['single','dropdown','department'].includes(q.type)){let opts=q.type==='department'?departments.map(d=>d.name||d.departmentName||'').filter(Boolean):(q.options||[]);return `<div class="editQuestion">${label}<select name="${attr(name)}"><option value="">未選擇</option>${opts.map(o=>`<option value="${attr(o)}" ${String(value??'')===String(o)?'selected':''}>${esc(o)}</option>`).join('')}</select></div>`}if(q.type==='long')return `<div class="editQuestion">${label}<textarea name="${attr(name)}">${esc(value??'')}</textarea></div>`;return `<div class="editQuestion">${label}<input type="text" name="${attr(name)}" value="${attr(value??'')}"></div>`}
function refreshEditMemberOptions(department){let select=$('editMember');select.innerHTML='<option value="">請選擇姓名</option>'+editMemberOptions(department);$('editEmployeeNo').value=''}
function refreshEditEmployee(){let m=members.find(x=>x.id===$('editMember').value);$('editEmployeeNo').value=m?.employeeNo||m?.empNo||''}
function closeResponseEditor(){$('responseEditMask').style.display='none';editingResponseId='';$('responseEditBody').innerHTML=''}
async function saveEditedResponse(event){event.preventDefault();let f=activeForm(),r=responses.find(x=>x.id===editingResponseId);if(!f||!r)return;let fd=new FormData(event.target),answers={};for(let q of(f.questions||[])){if(q.type==='image')continue;let name='edit_q_'+q.id;answers[q.id]=q.type==='multiple'?fd.getAll(name):String(fd.get(name)||'').trim()}let update={answers,updatedAt:firebase.firestore.FieldValue.serverTimestamp(),updatedBy:currentUser?.email||''};if(f.identityMode==='member'){let memberId=$('editMember').value,m=members.find(x=>x.id===memberId),departmentName=$('editDepartment').value;if(!m||!departmentName)return alert('請選擇部門與姓名');update={...update,departmentName,memberId,memberName:m.name||'',employeeNo:m.employeeNo||m.empNo||''}}let btn=$('saveResponseBtn');btn.disabled=true;btn.textContent='儲存中…';try{if(f.identityMode==='member'){let newId=`${f.id}__${update.memberId}`,newLock=doc('universalResponseLocks',newId),oldLockId=r.memberId?`${f.id}__${r.memberId}`:'';if(newId!==r.id){let [existing,locked]=await Promise.all([doc('universalResponses',newId).get(),newLock.get()]);if(existing.exists||locked.exists)throw new Error('所選同仁已有這份問卷的填寫資料');let {id,...oldData}=r,batch=db.batch();batch.set(doc('universalResponses',newId),{...oldData,...update});batch.delete(doc('universalResponses',r.id));if(oldLockId&&oldLockId!==newId)batch.delete(doc('universalResponseLocks',oldLockId));batch.set(newLock,{formId:f.id,memberId:update.memberId,createdAt:firebase.firestore.FieldValue.serverTimestamp()});await batch.commit()}else{let batch=db.batch();batch.update(doc('universalResponses',r.id),update);batch.set(newLock,{formId:f.id,memberId:update.memberId,createdAt:firebase.firestore.FieldValue.serverTimestamp()});await batch.commit()}}else await doc('universalResponses',r.id).update(update);closeResponseEditor();await loadResponses();renderAdmin();showPanel('resultsPanel');toast('填寫結果已更新')}catch(e){console.error(e);alert('更新失敗：'+(e.message||'請確認已發布 v1.10 Firestore 規則'))}finally{btn.disabled=false;btn.textContent='儲存變更'}}
async function deleteResponse(id){let r=responses.find(x=>x.id===id);if(!r)return;let who=[r.memberName,r.employeeNo].filter(Boolean).join('／')||'這筆未具名回覆';if(!confirm(`確定要刪除「${who}」的填寫結果嗎？\n刪除後同仁可以重新填寫。`))return;if(!confirm(`再次確認：即將永久刪除「${who}」的資料，此動作無法復原。`))return;try{let batch=db.batch();batch.delete(doc('universalResponses',id));if(r.formId&&r.memberId)batch.delete(doc('universalResponseLocks',`${r.formId}__${r.memberId}`));await batch.commit();await loadResponses();renderAdmin();showPanel('resultsPanel');toast('填寫結果與填寫鎖定已刪除，同仁可重新填寫')}catch(e){console.error(e);alert('刪除失敗，請確認管理員權限與 v1.10 Firestore 規則')}}
function selectionQuestions(f){return(f.questions||[]).filter(q=>['single','dropdown','department','multiple'].includes(q.type))}
function questionOptionLabels(q){return optionCounts(q).map(x=>x.label)}
function responseHasOption(r,q,option){let value=r.answers?.[q.id];return Array.isArray(value)?value.map(String).includes(String(option)):String(value??'')===String(option)}
function cleanSummarySheet(f){let total=responses.length,questions=selectionQuestions(f),maxCols=Math.max(4,...questions.map(q=>questionOptionLabels(q).length+2)),rows=[['問卷選項統計總表'],['問卷名稱',f.title],['總填寫份數',total],['匯出時間',new Date().toLocaleString('zh-TW')],[]],merges=[{s:{r:0,c:0},e:{r:0,c:maxCols-1}}];if(!questions.length){rows.push(['目前沒有可統計的選項題目']);merges.push({s:{r:5,c:0},e:{r:5,c:maxCols-1}})}for(let q of questions){let items=optionCounts(q),isMultiple=q.type==='multiple',titleRow=rows.length;rows.push([`${q.title}${isMultiple?'（複選）':''}`]);merges.push({s:{r:titleRow,c:0},e:{r:titleRow,c:Math.max(1,items.length+1)}});rows.push(['選項',...items.map(x=>x.label),'合計']);let sum=items.reduce((n,x)=>n+x.count,0);rows.push(['數量',...items.map(x=>x.count),sum]);rows.push(['占填寫人數',...items.map(x=>percentage(x.count,total)+'%'),isMultiple?'—':percentage(sum,total)+'%']);rows.push([])}let sheet=XLSX.utils.aoa_to_sheet(rows);sheet['!merges']=merges;sheet['!cols']=[{wch:18},...Array.from({length:maxCols-1},()=>({wch:13}))];return sheet}
function departmentCrossSheet(f){let questions=selectionQuestions(f),configured=departments.map(d=>d.name||d.departmentName||d.department||'').filter(Boolean),used=[...new Set(responses.map(r=>r.departmentName||'未填部門'))],depNames=[...configured.filter(d=>used.includes(d)),...used.filter(d=>!configured.includes(d))],maxCols=Math.max(4,...questions.map(q=>questionOptionLabels(q).length+2)),rows=[['部門 × 選項交叉統計'],['問卷名稱',f.title],['總填寫份數',responses.length],[]],merges=[{s:{r:0,c:0},e:{r:0,c:maxCols-1}}];if(f.identityMode!=='member'){rows.push(['此問卷未使用公司人員資料，因此沒有部門交叉統計。']);merges.push({s:{r:4,c:0},e:{r:4,c:maxCols-1}})}else if(!questions.length){rows.push(['目前沒有可統計的選項題目。']);merges.push({s:{r:4,c:0},e:{r:4,c:maxCols-1}})}else for(let q of questions){let options=questionOptionLabels(q),titleRow=rows.length;rows.push([q.title]);merges.push({s:{r:titleRow,c:0},e:{r:titleRow,c:Math.max(1,options.length+1)}});rows.push(['部門',...options,'合計']);for(let dep of depNames){let depResponses=responses.filter(r=>(r.departmentName||'未填部門')===dep),counts=options.map(o=>depResponses.filter(r=>responseHasOption(r,q,o)).length);rows.push([dep,...counts,counts.reduce((n,x)=>n+x,0)])}let totals=options.map(o=>responses.filter(r=>responseHasOption(r,q,o)).length);rows.push(['總計',...totals,totals.reduce((n,x)=>n+x,0)]);rows.push([])}let sheet=XLSX.utils.aoa_to_sheet(rows);sheet['!merges']=merges;sheet['!cols']=[{wch:18},...Array.from({length:maxCols-1},()=>({wch:13}))];return sheet}
function exportResults(){let f=activeForm();if(!f)return alert('請先選擇問卷');let qs=(f.questions||[]).filter(q=>q.type!=='image'),detailRows=responses.map(r=>{let row={'送出時間':r.submittedAtText||''};if(f.identityMode==='member'){row['部門']=r.departmentName||'';row['姓名']=r.memberName||'';row['員工編號']=r.employeeNo||''}qs.forEach(q=>row[q.title]=answerText(q,r));return row}),detailSheet=detailRows.length?XLSX.utils.json_to_sheet(detailRows):XLSX.utils.aoa_to_sheet([['目前尚無填寫明細']]);detailSheet['!cols']=[{wch:21},...(f.identityMode==='member'?[{wch:14},{wch:14},{wch:12}]:[]),...qs.map(()=>({wch:24}))];let wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,cleanSummarySheet(f),'選項統計總表');XLSX.utils.book_append_sheet(wb,departmentCrossSheet(f),'部門交叉統計');XLSX.utils.book_append_sheet(wb,detailSheet,'填寫明細');XLSX.writeFile(wb,(f.title||'問卷')+'_統計報表.xlsx')}

init().catch(e=>{console.error(e);frontMain.innerHTML='<div class="successCard"><h2>系統載入失敗</h2><p>'+esc(e.message||e)+'</p></div>'});
